HEADER_SEND = 10
HEADER_RECV = 11
PORT = 5050
FORMAT = 'utf-8'
DISCONNECT_MESSAGE = '!DISCONNECT'
IP_ADDR = '192.168.122.1'
NUMBER_OF_CLIENTS = 1
CYCLES = 3
FLAGS = {
    'ID': '0',
    'CONNECTED': '1',
    'GLOBAL WEIGHTS': '2',
    'LOCAL WEIGHTS': '3',
    '!DISCONNECT': '4',
}
INV_FLAGS = {
    '0': 'ID',
    '1': 'CONNECTED',
    '2': 'GLOBAL WEIGHTS',
    '3': 'LOCAL WEIGHTS',
    '4': '!DISCONNECT',
}
